name: CI
on:
  pull_request:
 
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: continuosintegration
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          
      - name: Test with coverage.py
        run: |
          cd backend/keplerapi
          coverage run manage.py test -v 2
