name: CI
on:
  pull_request:
 
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: continuosintegration
      DJANGO_SETTINGS_MODULE: keplerapi.tests.settings
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
        
      - name: Cache pip
        uses: actions/cache@v1.1.2
        id: cache
        with:
          path: ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Install Coveralls
        run: |
          pip install coveralls
          
      - name: Test with coverage.py
        run: |
          cd backend/keplerapi
          coverage run manage.py test -v 2
        
      - name: Generate Lcov report 
        run: |
          coveralls --output=report.json
          coveralls-lcov -v -n report.info > report.json

      - name: Send report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./report.json
