name: CI
on:
  pull_request:
 
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: continuosintegration
      DJANGO_SETTINGS_MODULE: keplerapi.tests.settings
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Update pip
        run: python -m pip install --upgrade pip
        
      - name: Cache pip
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-test
            
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Install Coverage
        run: pip install 'coverage==5.0.3'
          
      - name: Test with coverage.py
        run: |
          cd backend/keplerapi
          coverage run manage.py test -v 2
